### Custom build command: patch PE header
# Clang is actually good and doesn't need this workaround
IF(NOT CMAKE_CLANG_COMPILER AND MSVC AND NOT MSVC_VERSION LESS 1600 AND MACHINE_ARCH STREQUAL "X86")
    ADD_EXECUTABLE(patch_pe ${CMAKE_CURRENT_LIST_DIR}/cmake/patch_pe.c ${GLOBAL_ADDITIONAL_SOURCES})
    SET_TARGET_PROPERTIES(patch_pe PROPERTIES 
        COMPILE_FLAGS "${GLOBAL_COMPILE_FLAGS} ${EXECUTABLE_COMPILE_FLAGS}"
        LINK_FLAGS "${GLOBAL_LINK_FLAGS} ${EXECUTABLE_LINK_FLAGS}"
    )
    IF(GLOBAL_ADDITIONAL_LIBRARIES)
        TARGET_LINK_LIBRARIES(patch_pe ${GLOBAL_ADDITIONAL_LIBRARIES})
    ENDIF(GLOBAL_ADDITIONAL_LIBRARIES)
    IF(EXECUTABLE_DEPENDENCIES)
        ADD_DEPENDENCIES(patch_pe ${EXECUTABLE_DEPENDENCIES})
    ENDIF(EXECUTABLE_DEPENDENCIES)

    IF(COMMAND cmake_policy)
        SET(EXECUTABLE_LOCATION "$<TARGET_FILE:${EXECUTABLE_NAME}>")
        SET(PATCHER_LOCATION "$<TARGET_FILE:patch_pe>")
    ELSE(COMMAND cmake_policy)
        GET_TARGET_PROPERTY(EXECUTABLE_LOCATION ${EXECUTABLE_NAME} LOCATION)
        GET_TARGET_PROPERTY(PATCHER_LOCATION patch_pe LOCATION)
    ENDIF(COMMAND cmake_policy)

    ADD_CUSTOM_COMMAND(
        TARGET ${EXECUTABLE_NAME} POST_BUILD
        COMMAND "${PATCHER_LOCATION}" "${EXECUTABLE_LOCATION}"
    )
    ADD_DEPENDENCIES(${EXECUTABLE_NAME} patch_pe)
ENDIF(NOT CMAKE_CLANG_COMPILER AND MSVC AND NOT MSVC_VERSION LESS 1600 AND MACHINE_ARCH STREQUAL "X86")