SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_BUILD_TYPE Release)
SET(CMAKE_CROSSCOMPILING ON)

IF(NOT XWIN_DIR)
	SET(XWIN_DIR "/xwin")
ENDIF(NOT XWIN_DIR)
IF(NOT EXISTS "${XWIN_DIR}")
	MESSAGE(FATAL_ERROR "XWin directory ${XWIN_DIR} is not correct or does not exist. XWin is needed to build with clang-cl.")
ENDIF(NOT EXISTS "${XWIN_DIR}")	

IF(NOT TARGET_ARCH)
	SET(TARGET_ARCH "X86")
ENDIF(NOT TARGET_ARCH)

IF(NOT TARGET_ARCH STREQUAL "X86" AND NOT TARGET_ARCH STREQUAL "X64")
	MESSAGE(FATAL_ERROR "Cross compiling is only supported for X86 and X64 targets.")
ENDIF(NOT TARGET_ARCH STREQUAL "X86" AND NOT TARGET_ARCH STREQUAL "X64")

IF(TARGET_ARCH STREQUAL "X86")
	SET(CLANG_TARGET_ARCH i686)
	SET(TOOLCHAIN_PREFIX i686-w64-mingw32)
ENDIF(TARGET_ARCH STREQUAL "X86")
IF(TARGET_ARCH STREQUAL "X64")
	SET(CLANG_TARGET_ARCH x86_64)
	SET(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
ENDIF(TARGET_ARCH STREQUAL "X64")
STRING(TOLOWER "${TARGET_ARCH}" WINSDK_TARGET_ARCH)

SET(CMAKE_C_COMPILER clang-cl)
SET(CMAKE_CXX_COMPILER clang-cl)
SET(CMAKE_LINKER lld-link)
SET(CMAKE_RC_COMPILER llvm-rc)
SET(CMAKE_LIB_COMPILER llvm-lib)

# define libs and includes
SET(CLANG_CL_FLAGS "--target=${CLANG_TARGET_ARCH}-pc-windows-msvc -fms-compatibility-version=19.11 -Wno-ignored-attributes")
SET(CLANG_CL_INCLUDES "-imsvc ${XWIN_DIR}/crt/include -imsvc ${XWIN_DIR}/sdk/include/ucrt -imsvc ${XWIN_DIR}/sdk/include/shared -imsvc ${XWIN_DIR}/sdk/include/um")
SET(LLD_LINK_FLAGS "")
SET(LLD_LINK_PATHS "-libpath:${XWIN_DIR}/crt/lib/${WINSDK_TARGET_ARCH} -libpath:${XWIN_DIR}/sdk/lib/ucrt/${WINSDK_TARGET_ARCH} -libpath:${XWIN_DIR}/sdk/lib/um/${WINSDK_TARGET_ARCH}")

SET(CMAKE_C_FLAGS_INIT "${CLANG_CL_FLAGS} ${CLANG_CL_INCLUDES}")
SET(CMAKE_CXX_FLAGS_INIT "${CLANG_CL_FLAGS} ${CLANG_CL_INCLUDES}")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "${LLD_LINK_FLAGS} ${LLD_LINK_PATHS}")
SET(CMAKE_SHARED_LINKER_FLAGS_INIT "${LLD_LINK_FLAGS} ${LLD_LINK_PATHS}")
SET(CMAKE_MODULE_LINKER_FLAGS_INIT "${LLD_LINK_FLAGS} ${LLD_LINK_PATHS}")

set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)

SET(CMAKE_FIND_ROOT_PATH "${XWIN_DIR}")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)