SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_BUILD_TYPE Release)
SET(CMAKE_CROSSCOMPILING ON)

IF(NOT TARGET_ARCH)
	SET(TARGET_ARCH "X86")
ENDIF(NOT TARGET_ARCH)

IF(NOT TARGET_ARCH STREQUAL "X86" AND NOT TARGET_ARCH STREQUAL "X64")
	MESSAGE(FATAL_ERROR "Cross compiling is only supported for X86 and X64 targets.")
ENDIF(NOT TARGET_ARCH STREQUAL "X86" AND NOT TARGET_ARCH STREQUAL "X64")

IF(TARGET_ARCH STREQUAL "X86")
	SET(TOOLCHAIN_PREFIX i686-w64-mingw32)
ENDIF(TARGET_ARCH STREQUAL "X86")
IF(TARGET_ARCH STREQUAL "X64")
	SET(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
ENDIF(TARGET_ARCH STREQUAL "X64")

SET(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
SET(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
SET(CMAKE_LIB_COMPILER ${TOOLCHAIN_PREFIX}-dlltool)

SET(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)