MACRO(ADD_CRT_LIBRARY CRT_LOCATION)
    SET(TARGET_NAME crt)

    ### Generate CRT lib
    IF(USE_OLD_CRT)
        SET(CRT_DEF "${CRT_LOCATION}/crtdll.def")
        SET(CRT_BASENAME "crtdll")
        IF(MSVC)
            SET(GLOBAL_COMPILE_FLAGS "${GLOBAL_COMPILE_FLAGS} /DUSE_OLD_CRT")
        ELSE(MSVC)
            SET(GLOBAL_COMPILE_FLAGS "${GLOBAL_COMPILE_FLAGS} -DUSE_OLD_CRT")
        ENDIF(MSVC)
    ELSE(USE_OLD_CRT)
        SET(CRT_DEF "${CRT_LOCATION}/msvcrt.def")
        SET(CRT_BASENAME "msvcrt")
    ENDIF(USE_OLD_CRT)

    IF(MSVC)
        SET(LIB_EXT ".lib")
        SET(CRT_LIB "${CMAKE_CURRENT_BINARY_DIR}/${CRT_BASENAME}${LIB_EXT}")
        SET(LIB_CMD ${CMAKE_LIB_COMPILER} /nologo /def:"${CRT_DEF}" /out:"${CRT_LIB}" /machine:${MACHINE_ARCH})
    ELSE(MSVC)
        SET(LIB_EXT ".a")
        SET(CRT_LIB "${CMAKE_CURRENT_BINARY_DIR}/lib${CRT_BASENAME}${LIB_EXT}")
        SET(LIB_CMD ${CMAKE_LIB_COMPILER} -d "${CRT_DEF}" -l "${CRT_LIB}" -m ${GNU_MACHINE_ARCH})
    ENDIF(MSVC)

    ADD_CUSTOM_COMMAND(
        OUTPUT "${CRT_LIB}"
        COMMAND ${LIB_CMD}
        DEPENDS "${CRT_DEF}"
    )

    ADD_CUSTOM_TARGET(${TARGET_NAME} DEPENDS "${CRT_LIB}")

    LIST(APPEND EXECUTABLE_DEPENDENCIES ${TARGET_NAME})
    LIST(APPEND DLL_DEPENDENCIES ${TARGET_NAME})

    ### Add CRT base
    LIST(APPEND GLOBAL_ADDITIONAL_SOURCES "${CRT_LOCATION}/crt.c")
    LIST(APPEND GLOBAL_ADDITIONAL_LIBRARIES "${CRT_LIB}")

    ### Define entry point
    IF(MSVC)
        SET(DLL_COMPILE_FLAGS "${DLL_COMPILE_FLAGS} /DCRT_IS_DLL")
        SET(EXECUTABLE_LINK_FLAGS "${EXECUTABLE_LINK_FLAGS} /entry:mainCRTStartup")
        SET(DLL_LINK_FLAGS "${DLL_LINK_FLAGS} /entry:DllMainCRTStartup")
    ELSE(MSVC)
        SET(DLL_COMPILE_FLAGS "${DLL_COMPILE_FLAGS} -DCRT_IS_DLL")
        IF(MACHINE_ARCH STREQUAL "X86")
            SET(EXECUTABLE_LINK_FLAGS "${EXECUTABLE_LINK_FLAGS} -Wl,-e,_mainCRTStartup")
            SET(DLL_LINK_FLAGS "${DLL_LINK_FLAGS} -Wl,-e,_DllMainCRTStartup@12")
        ELSE(MACHINE_ARCH STREQUAL "X86")
            SET(EXECUTABLE_LINK_FLAGS "${EXECUTABLE_LINK_FLAGS} -Wl,-e,mainCRTStartup")
            SET(DLL_LINK_FLAGS "${DLL_LINK_FLAGS} -Wl,-e,DllMainCRTStartup")
        ENDIF(MACHINE_ARCH STREQUAL "X86")    
    ENDIF(MSVC)
ENDMACRO(ADD_CRT_LIBRARY)